package main

import (
	"log"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"

	_ "agentic-template/docs" // This will be generated by swag init
)

// @title           Agentic Template API
// @version         1.0
// @description     This is a sample full-stack API server for AI agent collaboration.
// @host            localhost:8081
// @BasePath        /

// User represents the database model for a user
type User struct {
	gorm.Model
	Name  string `json:"name" example:"John Doe"`
	Email string `json:"email" gorm:"unique" example:"john@example.com"`
}

var db *gorm.DB

func initDB() {
	// Load .env file if it exists
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, using environment variables")
	}

	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "app_user:app_password@tcp(localhost:3306)/app_db?charset=utf8mb4&parseTime=True&loc=Local"
	}

	var err error
	db, err = gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Printf("Warning: Failed to connect to database: %v. Running in memory-only mode for some features.", err)
		return
	}

	// Auto Migrate
	db.AutoMigrate(&User{})
}

func main() {
	initDB()

	r := gin.Default()

	// CORS Middleware
	r.Use(func(c *gin.Context) {
		c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
		c.Writer.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}
		c.Next()
	})

	// @Summary      Health Check
	// @Description  Check backend health status
	// @Tags         system
	// @Produce      json
	// @Success      200  {object}  map[string]string
	// @Router       /ping [get]
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "pong",
			"status":  "healthy",
		})
	})

	// @Summary      List Users
	// @Description  Get all registered users
	// @Tags         users
	// @Produce      json
	// @Success      200  {array}   User
	// @Router       /api/users [get]
	r.GET("/api/users", func(c *gin.Context) {
		var users []User
		if db != nil {
			db.Find(&users)
		}
		c.JSON(http.StatusOK, users)
	})

	// Swagger documentation
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	port := os.Getenv("PORT")
	if port == "" {
		port = "8081"
	}

	log.Printf("Server starting on port %s", port)
	log.Printf("Swagger UI available at http://localhost:%s/swagger/index.html", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
